//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace StyledBlazor
{
    public partial record Styled
    {
        /// <summary>
        /// Creates a new styled component with a &lt;A&gt; tag
        /// </summary>
        public record A : Styled
        {
            public A() : base("a")
            {
            }

            public A(string cssClass) : base("A", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Abbr&gt; tag
        /// </summary>
        public record Abbr : Styled
        {
            public Abbr() : base("abbr")
            {
            }

            public Abbr(string cssClass) : base("Abbr", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Address&gt; tag
        /// </summary>
        public record Address : Styled
        {
            public Address() : base("address")
            {
            }

            public Address(string cssClass) : base("Address", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Area&gt; tag
        /// </summary>
        public record Area : Styled
        {
            public Area() : base("area")
            {
            }

            public Area(string cssClass) : base("Area", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Article&gt; tag
        /// </summary>
        public record Article : Styled
        {
            public Article() : base("article")
            {
            }

            public Article(string cssClass) : base("Article", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Aside&gt; tag
        /// </summary>
        public record Aside : Styled
        {
            public Aside() : base("aside")
            {
            }

            public Aside(string cssClass) : base("Aside", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Audio&gt; tag
        /// </summary>
        public record Audio : Styled
        {
            public Audio() : base("audio")
            {
            }

            public Audio(string cssClass) : base("Audio", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;B&gt; tag
        /// </summary>
        public record B : Styled
        {
            public B() : base("b")
            {
            }

            public B(string cssClass) : base("B", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Base&gt; tag
        /// </summary>
        public record Base : Styled
        {
            public Base() : base("base")
            {
            }

            public Base(string cssClass) : base("Base", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Bdi&gt; tag
        /// </summary>
        public record Bdi : Styled
        {
            public Bdi() : base("bdi")
            {
            }

            public Bdi(string cssClass) : base("Bdi", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Bdo&gt; tag
        /// </summary>
        public record Bdo : Styled
        {
            public Bdo() : base("bdo")
            {
            }

            public Bdo(string cssClass) : base("Bdo", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Big&gt; tag
        /// </summary>
        public record Big : Styled
        {
            public Big() : base("big")
            {
            }

            public Big(string cssClass) : base("Big", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Blockquote&gt; tag
        /// </summary>
        public record Blockquote : Styled
        {
            public Blockquote() : base("blockquote")
            {
            }

            public Blockquote(string cssClass) : base("Blockquote", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Body&gt; tag
        /// </summary>
        public record Body : Styled
        {
            public Body() : base("body")
            {
            }

            public Body(string cssClass) : base("Body", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Br&gt; tag
        /// </summary>
        public record Br : Styled
        {
            public Br() : base("br")
            {
            }

            public Br(string cssClass) : base("Br", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Button&gt; tag
        /// </summary>
        public record Button : Styled
        {
            public Button() : base("button")
            {
            }

            public Button(string cssClass) : base("Button", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Canvas&gt; tag
        /// </summary>
        public record Canvas : Styled
        {
            public Canvas() : base("canvas")
            {
            }

            public Canvas(string cssClass) : base("Canvas", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Caption&gt; tag
        /// </summary>
        public record Caption : Styled
        {
            public Caption() : base("caption")
            {
            }

            public Caption(string cssClass) : base("Caption", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Cite&gt; tag
        /// </summary>
        public record Cite : Styled
        {
            public Cite() : base("cite")
            {
            }

            public Cite(string cssClass) : base("Cite", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Code&gt; tag
        /// </summary>
        public record Code : Styled
        {
            public Code() : base("code")
            {
            }

            public Code(string cssClass) : base("Code", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Col&gt; tag
        /// </summary>
        public record Col : Styled
        {
            public Col() : base("col")
            {
            }

            public Col(string cssClass) : base("Col", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Colgroup&gt; tag
        /// </summary>
        public record Colgroup : Styled
        {
            public Colgroup() : base("colgroup")
            {
            }

            public Colgroup(string cssClass) : base("Colgroup", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Data&gt; tag
        /// </summary>
        public record Data : Styled
        {
            public Data() : base("data")
            {
            }

            public Data(string cssClass) : base("Data", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Datalist&gt; tag
        /// </summary>
        public record Datalist : Styled
        {
            public Datalist() : base("datalist")
            {
            }

            public Datalist(string cssClass) : base("Datalist", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Dd&gt; tag
        /// </summary>
        public record Dd : Styled
        {
            public Dd() : base("dd")
            {
            }

            public Dd(string cssClass) : base("Dd", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Del&gt; tag
        /// </summary>
        public record Del : Styled
        {
            public Del() : base("del")
            {
            }

            public Del(string cssClass) : base("Del", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Details&gt; tag
        /// </summary>
        public record Details : Styled
        {
            public Details() : base("details")
            {
            }

            public Details(string cssClass) : base("Details", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Dfn&gt; tag
        /// </summary>
        public record Dfn : Styled
        {
            public Dfn() : base("dfn")
            {
            }

            public Dfn(string cssClass) : base("Dfn", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Dialog&gt; tag
        /// </summary>
        public record Dialog : Styled
        {
            public Dialog() : base("dialog")
            {
            }

            public Dialog(string cssClass) : base("Dialog", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Div&gt; tag
        /// </summary>
        public record Div : Styled
        {
            public Div() : base("div")
            {
            }

            public Div(string cssClass) : base("Div", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Dl&gt; tag
        /// </summary>
        public record Dl : Styled
        {
            public Dl() : base("dl")
            {
            }

            public Dl(string cssClass) : base("Dl", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Dt&gt; tag
        /// </summary>
        public record Dt : Styled
        {
            public Dt() : base("dt")
            {
            }

            public Dt(string cssClass) : base("Dt", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Em&gt; tag
        /// </summary>
        public record Em : Styled
        {
            public Em() : base("em")
            {
            }

            public Em(string cssClass) : base("Em", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Embed&gt; tag
        /// </summary>
        public record Embed : Styled
        {
            public Embed() : base("embed")
            {
            }

            public Embed(string cssClass) : base("Embed", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Fieldset&gt; tag
        /// </summary>
        public record Fieldset : Styled
        {
            public Fieldset() : base("fieldset")
            {
            }

            public Fieldset(string cssClass) : base("Fieldset", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Figcaption&gt; tag
        /// </summary>
        public record Figcaption : Styled
        {
            public Figcaption() : base("figcaption")
            {
            }

            public Figcaption(string cssClass) : base("Figcaption", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Figure&gt; tag
        /// </summary>
        public record Figure : Styled
        {
            public Figure() : base("figure")
            {
            }

            public Figure(string cssClass) : base("Figure", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Footer&gt; tag
        /// </summary>
        public record Footer : Styled
        {
            public Footer() : base("footer")
            {
            }

            public Footer(string cssClass) : base("Footer", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Form&gt; tag
        /// </summary>
        public record Form : Styled
        {
            public Form() : base("form")
            {
            }

            public Form(string cssClass) : base("Form", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H1&gt; tag
        /// </summary>
        public record H1 : Styled
        {
            public H1() : base("h1")
            {
            }

            public H1(string cssClass) : base("H1", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H2&gt; tag
        /// </summary>
        public record H2 : Styled
        {
            public H2() : base("h2")
            {
            }

            public H2(string cssClass) : base("H2", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H3&gt; tag
        /// </summary>
        public record H3 : Styled
        {
            public H3() : base("h3")
            {
            }

            public H3(string cssClass) : base("H3", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H4&gt; tag
        /// </summary>
        public record H4 : Styled
        {
            public H4() : base("h4")
            {
            }

            public H4(string cssClass) : base("H4", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H5&gt; tag
        /// </summary>
        public record H5 : Styled
        {
            public H5() : base("h5")
            {
            }

            public H5(string cssClass) : base("H5", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;H6&gt; tag
        /// </summary>
        public record H6 : Styled
        {
            public H6() : base("h6")
            {
            }

            public H6(string cssClass) : base("H6", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Head&gt; tag
        /// </summary>
        public record Head : Styled
        {
            public Head() : base("head")
            {
            }

            public Head(string cssClass) : base("Head", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Header&gt; tag
        /// </summary>
        public record Header : Styled
        {
            public Header() : base("header")
            {
            }

            public Header(string cssClass) : base("Header", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Hgroup&gt; tag
        /// </summary>
        public record Hgroup : Styled
        {
            public Hgroup() : base("hgroup")
            {
            }

            public Hgroup(string cssClass) : base("Hgroup", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Hr&gt; tag
        /// </summary>
        public record Hr : Styled
        {
            public Hr() : base("hr")
            {
            }

            public Hr(string cssClass) : base("Hr", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Html&gt; tag
        /// </summary>
        public record Html : Styled
        {
            public Html() : base("html")
            {
            }

            public Html(string cssClass) : base("Html", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;I&gt; tag
        /// </summary>
        public record I : Styled
        {
            public I() : base("i")
            {
            }

            public I(string cssClass) : base("I", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Iframe&gt; tag
        /// </summary>
        public record Iframe : Styled
        {
            public Iframe() : base("iframe")
            {
            }

            public Iframe(string cssClass) : base("Iframe", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Img&gt; tag
        /// </summary>
        public record Img : Styled
        {
            public Img() : base("img")
            {
            }

            public Img(string cssClass) : base("Img", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Input&gt; tag
        /// </summary>
        public record Input : Styled
        {
            public Input() : base("input")
            {
            }

            public Input(string cssClass) : base("Input", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Ins&gt; tag
        /// </summary>
        public record Ins : Styled
        {
            public Ins() : base("ins")
            {
            }

            public Ins(string cssClass) : base("Ins", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Kbd&gt; tag
        /// </summary>
        public record Kbd : Styled
        {
            public Kbd() : base("kbd")
            {
            }

            public Kbd(string cssClass) : base("Kbd", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Keygen&gt; tag
        /// </summary>
        public record Keygen : Styled
        {
            public Keygen() : base("keygen")
            {
            }

            public Keygen(string cssClass) : base("Keygen", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Label&gt; tag
        /// </summary>
        public record Label : Styled
        {
            public Label() : base("label")
            {
            }

            public Label(string cssClass) : base("Label", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Legend&gt; tag
        /// </summary>
        public record Legend : Styled
        {
            public Legend() : base("legend")
            {
            }

            public Legend(string cssClass) : base("Legend", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Li&gt; tag
        /// </summary>
        public record Li : Styled
        {
            public Li() : base("li")
            {
            }

            public Li(string cssClass) : base("Li", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Link&gt; tag
        /// </summary>
        public record Link : Styled
        {
            public Link() : base("link")
            {
            }

            public Link(string cssClass) : base("Link", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Main&gt; tag
        /// </summary>
        public record Main : Styled
        {
            public Main() : base("main")
            {
            }

            public Main(string cssClass) : base("Main", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Map&gt; tag
        /// </summary>
        public record Map : Styled
        {
            public Map() : base("map")
            {
            }

            public Map(string cssClass) : base("Map", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Mark&gt; tag
        /// </summary>
        public record Mark : Styled
        {
            public Mark() : base("mark")
            {
            }

            public Mark(string cssClass) : base("Mark", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Marquee&gt; tag
        /// </summary>
        public record Marquee : Styled
        {
            public Marquee() : base("marquee")
            {
            }

            public Marquee(string cssClass) : base("Marquee", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Menu&gt; tag
        /// </summary>
        public record Menu : Styled
        {
            public Menu() : base("menu")
            {
            }

            public Menu(string cssClass) : base("Menu", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Menuitem&gt; tag
        /// </summary>
        public record Menuitem : Styled
        {
            public Menuitem() : base("menuitem")
            {
            }

            public Menuitem(string cssClass) : base("Menuitem", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Meta&gt; tag
        /// </summary>
        public record Meta : Styled
        {
            public Meta() : base("meta")
            {
            }

            public Meta(string cssClass) : base("Meta", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Meter&gt; tag
        /// </summary>
        public record Meter : Styled
        {
            public Meter() : base("meter")
            {
            }

            public Meter(string cssClass) : base("Meter", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Nav&gt; tag
        /// </summary>
        public record Nav : Styled
        {
            public Nav() : base("nav")
            {
            }

            public Nav(string cssClass) : base("Nav", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Noscript&gt; tag
        /// </summary>
        public record Noscript : Styled
        {
            public Noscript() : base("noscript")
            {
            }

            public Noscript(string cssClass) : base("Noscript", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Object&gt; tag
        /// </summary>
        public record Object : Styled
        {
            public Object() : base("object")
            {
            }

            public Object(string cssClass) : base("Object", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Ol&gt; tag
        /// </summary>
        public record Ol : Styled
        {
            public Ol() : base("ol")
            {
            }

            public Ol(string cssClass) : base("Ol", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Optgroup&gt; tag
        /// </summary>
        public record Optgroup : Styled
        {
            public Optgroup() : base("optgroup")
            {
            }

            public Optgroup(string cssClass) : base("Optgroup", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Option&gt; tag
        /// </summary>
        public record Option : Styled
        {
            public Option() : base("option")
            {
            }

            public Option(string cssClass) : base("Option", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Output&gt; tag
        /// </summary>
        public record Output : Styled
        {
            public Output() : base("output")
            {
            }

            public Output(string cssClass) : base("Output", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;P&gt; tag
        /// </summary>
        public record P : Styled
        {
            public P() : base("p")
            {
            }

            public P(string cssClass) : base("P", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Param&gt; tag
        /// </summary>
        public record Param : Styled
        {
            public Param() : base("param")
            {
            }

            public Param(string cssClass) : base("Param", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Picture&gt; tag
        /// </summary>
        public record Picture : Styled
        {
            public Picture() : base("picture")
            {
            }

            public Picture(string cssClass) : base("Picture", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Pre&gt; tag
        /// </summary>
        public record Pre : Styled
        {
            public Pre() : base("pre")
            {
            }

            public Pre(string cssClass) : base("Pre", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Progress&gt; tag
        /// </summary>
        public record Progress : Styled
        {
            public Progress() : base("progress")
            {
            }

            public Progress(string cssClass) : base("Progress", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Q&gt; tag
        /// </summary>
        public record Q : Styled
        {
            public Q() : base("q")
            {
            }

            public Q(string cssClass) : base("Q", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Rp&gt; tag
        /// </summary>
        public record Rp : Styled
        {
            public Rp() : base("rp")
            {
            }

            public Rp(string cssClass) : base("Rp", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Rt&gt; tag
        /// </summary>
        public record Rt : Styled
        {
            public Rt() : base("rt")
            {
            }

            public Rt(string cssClass) : base("Rt", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Ruby&gt; tag
        /// </summary>
        public record Ruby : Styled
        {
            public Ruby() : base("ruby")
            {
            }

            public Ruby(string cssClass) : base("Ruby", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;S&gt; tag
        /// </summary>
        public record S : Styled
        {
            public S() : base("s")
            {
            }

            public S(string cssClass) : base("S", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Samp&gt; tag
        /// </summary>
        public record Samp : Styled
        {
            public Samp() : base("samp")
            {
            }

            public Samp(string cssClass) : base("Samp", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Script&gt; tag
        /// </summary>
        public record Script : Styled
        {
            public Script() : base("script")
            {
            }

            public Script(string cssClass) : base("Script", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Section&gt; tag
        /// </summary>
        public record Section : Styled
        {
            public Section() : base("section")
            {
            }

            public Section(string cssClass) : base("Section", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Select&gt; tag
        /// </summary>
        public record Select : Styled
        {
            public Select() : base("select")
            {
            }

            public Select(string cssClass) : base("Select", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Small&gt; tag
        /// </summary>
        public record Small : Styled
        {
            public Small() : base("small")
            {
            }

            public Small(string cssClass) : base("Small", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Source&gt; tag
        /// </summary>
        public record Source : Styled
        {
            public Source() : base("source")
            {
            }

            public Source(string cssClass) : base("Source", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Span&gt; tag
        /// </summary>
        public record Span : Styled
        {
            public Span() : base("span")
            {
            }

            public Span(string cssClass) : base("Span", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Strong&gt; tag
        /// </summary>
        public record Strong : Styled
        {
            public Strong() : base("strong")
            {
            }

            public Strong(string cssClass) : base("Strong", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Style&gt; tag
        /// </summary>
        public record Style : Styled
        {
            public Style() : base("style")
            {
            }

            public Style(string cssClass) : base("Style", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Sub&gt; tag
        /// </summary>
        public record Sub : Styled
        {
            public Sub() : base("sub")
            {
            }

            public Sub(string cssClass) : base("Sub", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Summary&gt; tag
        /// </summary>
        public record Summary : Styled
        {
            public Summary() : base("summary")
            {
            }

            public Summary(string cssClass) : base("Summary", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Sup&gt; tag
        /// </summary>
        public record Sup : Styled
        {
            public Sup() : base("sup")
            {
            }

            public Sup(string cssClass) : base("Sup", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Table&gt; tag
        /// </summary>
        public record Table : Styled
        {
            public Table() : base("table")
            {
            }

            public Table(string cssClass) : base("Table", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Tbody&gt; tag
        /// </summary>
        public record Tbody : Styled
        {
            public Tbody() : base("tbody")
            {
            }

            public Tbody(string cssClass) : base("Tbody", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Td&gt; tag
        /// </summary>
        public record Td : Styled
        {
            public Td() : base("td")
            {
            }

            public Td(string cssClass) : base("Td", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Textarea&gt; tag
        /// </summary>
        public record Textarea : Styled
        {
            public Textarea() : base("textarea")
            {
            }

            public Textarea(string cssClass) : base("Textarea", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Tfoot&gt; tag
        /// </summary>
        public record Tfoot : Styled
        {
            public Tfoot() : base("tfoot")
            {
            }

            public Tfoot(string cssClass) : base("Tfoot", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Th&gt; tag
        /// </summary>
        public record Th : Styled
        {
            public Th() : base("th")
            {
            }

            public Th(string cssClass) : base("Th", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Thead&gt; tag
        /// </summary>
        public record Thead : Styled
        {
            public Thead() : base("thead")
            {
            }

            public Thead(string cssClass) : base("Thead", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Time&gt; tag
        /// </summary>
        public record Time : Styled
        {
            public Time() : base("time")
            {
            }

            public Time(string cssClass) : base("Time", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Title&gt; tag
        /// </summary>
        public record Title : Styled
        {
            public Title() : base("title")
            {
            }

            public Title(string cssClass) : base("Title", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Tr&gt; tag
        /// </summary>
        public record Tr : Styled
        {
            public Tr() : base("tr")
            {
            }

            public Tr(string cssClass) : base("Tr", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Track&gt; tag
        /// </summary>
        public record Track : Styled
        {
            public Track() : base("track")
            {
            }

            public Track(string cssClass) : base("Track", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;U&gt; tag
        /// </summary>
        public record U : Styled
        {
            public U() : base("u")
            {
            }

            public U(string cssClass) : base("U", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Ul&gt; tag
        /// </summary>
        public record Ul : Styled
        {
            public Ul() : base("ul")
            {
            }

            public Ul(string cssClass) : base("Ul", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Var&gt; tag
        /// </summary>
        public record Var : Styled
        {
            public Var() : base("var")
            {
            }

            public Var(string cssClass) : base("Var", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Video&gt; tag
        /// </summary>
        public record Video : Styled
        {
            public Video() : base("video")
            {
            }

            public Video(string cssClass) : base("Video", cssClass)
            {
            }
        }

        /// <summary>
        /// Creates a new styled component with a &lt;Wbr&gt; tag
        /// </summary>
        public record Wbr : Styled
        {
            public Wbr() : base("wbr")
            {
            }

            public Wbr(string cssClass) : base("Wbr", cssClass)
            {
            }
        }
    }
}
