//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StyledBlazor
{
    public partial record Styled
    {
        public record A : Styled
        {
            public A() : base("a")
            {
            }

            public A(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("A", cssClassAction)
            {
            }

            public A(string cssClass) : base("A", cssClass)
            {
            }
        }

        public record Abbr : Styled
        {
            public Abbr() : base("abbr")
            {
            }

            public Abbr(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Abbr", cssClassAction)
            {
            }

            public Abbr(string cssClass) : base("Abbr", cssClass)
            {
            }
        }

        public record Address : Styled
        {
            public Address() : base("address")
            {
            }

            public Address(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Address", cssClassAction)
            {
            }

            public Address(string cssClass) : base("Address", cssClass)
            {
            }
        }

        public record Area : Styled
        {
            public Area() : base("area")
            {
            }

            public Area(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Area", cssClassAction)
            {
            }

            public Area(string cssClass) : base("Area", cssClass)
            {
            }
        }

        public record Article : Styled
        {
            public Article() : base("article")
            {
            }

            public Article(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Article", cssClassAction)
            {
            }

            public Article(string cssClass) : base("Article", cssClass)
            {
            }
        }

        public record Aside : Styled
        {
            public Aside() : base("aside")
            {
            }

            public Aside(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Aside", cssClassAction)
            {
            }

            public Aside(string cssClass) : base("Aside", cssClass)
            {
            }
        }

        public record Audio : Styled
        {
            public Audio() : base("audio")
            {
            }

            public Audio(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Audio", cssClassAction)
            {
            }

            public Audio(string cssClass) : base("Audio", cssClass)
            {
            }
        }

        public record B : Styled
        {
            public B() : base("b")
            {
            }

            public B(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("B", cssClassAction)
            {
            }

            public B(string cssClass) : base("B", cssClass)
            {
            }
        }

        public record Base : Styled
        {
            public Base() : base("base")
            {
            }

            public Base(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Base", cssClassAction)
            {
            }

            public Base(string cssClass) : base("Base", cssClass)
            {
            }
        }

        public record Bdi : Styled
        {
            public Bdi() : base("bdi")
            {
            }

            public Bdi(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Bdi", cssClassAction)
            {
            }

            public Bdi(string cssClass) : base("Bdi", cssClass)
            {
            }
        }

        public record Bdo : Styled
        {
            public Bdo() : base("bdo")
            {
            }

            public Bdo(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Bdo", cssClassAction)
            {
            }

            public Bdo(string cssClass) : base("Bdo", cssClass)
            {
            }
        }

        public record Big : Styled
        {
            public Big() : base("big")
            {
            }

            public Big(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Big", cssClassAction)
            {
            }

            public Big(string cssClass) : base("Big", cssClass)
            {
            }
        }

        public record Blockquote : Styled
        {
            public Blockquote() : base("blockquote")
            {
            }

            public Blockquote(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Blockquote", cssClassAction)
            {
            }

            public Blockquote(string cssClass) : base("Blockquote", cssClass)
            {
            }
        }

        public record Body : Styled
        {
            public Body() : base("body")
            {
            }

            public Body(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Body", cssClassAction)
            {
            }

            public Body(string cssClass) : base("Body", cssClass)
            {
            }
        }

        public record Br : Styled
        {
            public Br() : base("br")
            {
            }

            public Br(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Br", cssClassAction)
            {
            }

            public Br(string cssClass) : base("Br", cssClass)
            {
            }
        }

        public record Button : Styled
        {
            public Button() : base("button")
            {
            }

            public Button(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Button", cssClassAction)
            {
            }

            public Button(string cssClass) : base("Button", cssClass)
            {
            }
        }

        public record Canvas : Styled
        {
            public Canvas() : base("canvas")
            {
            }

            public Canvas(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Canvas", cssClassAction)
            {
            }

            public Canvas(string cssClass) : base("Canvas", cssClass)
            {
            }
        }

        public record Caption : Styled
        {
            public Caption() : base("caption")
            {
            }

            public Caption(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Caption", cssClassAction)
            {
            }

            public Caption(string cssClass) : base("Caption", cssClass)
            {
            }
        }

        public record Cite : Styled
        {
            public Cite() : base("cite")
            {
            }

            public Cite(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Cite", cssClassAction)
            {
            }

            public Cite(string cssClass) : base("Cite", cssClass)
            {
            }
        }

        public record Code : Styled
        {
            public Code() : base("code")
            {
            }

            public Code(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Code", cssClassAction)
            {
            }

            public Code(string cssClass) : base("Code", cssClass)
            {
            }
        }

        public record Col : Styled
        {
            public Col() : base("col")
            {
            }

            public Col(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Col", cssClassAction)
            {
            }

            public Col(string cssClass) : base("Col", cssClass)
            {
            }
        }

        public record Colgroup : Styled
        {
            public Colgroup() : base("colgroup")
            {
            }

            public Colgroup(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Colgroup", cssClassAction)
            {
            }

            public Colgroup(string cssClass) : base("Colgroup", cssClass)
            {
            }
        }

        public record Data : Styled
        {
            public Data() : base("data")
            {
            }

            public Data(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Data", cssClassAction)
            {
            }

            public Data(string cssClass) : base("Data", cssClass)
            {
            }
        }

        public record Datalist : Styled
        {
            public Datalist() : base("datalist")
            {
            }

            public Datalist(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Datalist", cssClassAction)
            {
            }

            public Datalist(string cssClass) : base("Datalist", cssClass)
            {
            }
        }

        public record Dd : Styled
        {
            public Dd() : base("dd")
            {
            }

            public Dd(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Dd", cssClassAction)
            {
            }

            public Dd(string cssClass) : base("Dd", cssClass)
            {
            }
        }

        public record Del : Styled
        {
            public Del() : base("del")
            {
            }

            public Del(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Del", cssClassAction)
            {
            }

            public Del(string cssClass) : base("Del", cssClass)
            {
            }
        }

        public record Details : Styled
        {
            public Details() : base("details")
            {
            }

            public Details(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Details", cssClassAction)
            {
            }

            public Details(string cssClass) : base("Details", cssClass)
            {
            }
        }

        public record Dfn : Styled
        {
            public Dfn() : base("dfn")
            {
            }

            public Dfn(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Dfn", cssClassAction)
            {
            }

            public Dfn(string cssClass) : base("Dfn", cssClass)
            {
            }
        }

        public record Dialog : Styled
        {
            public Dialog() : base("dialog")
            {
            }

            public Dialog(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Dialog", cssClassAction)
            {
            }

            public Dialog(string cssClass) : base("Dialog", cssClass)
            {
            }
        }

        public record Div : Styled
        {
            public Div() : base("div")
            {
            }

            public Div(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Div", cssClassAction)
            {
            }

            public Div(string cssClass) : base("Div", cssClass)
            {
            }
        }

        public record Dl : Styled
        {
            public Dl() : base("dl")
            {
            }

            public Dl(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Dl", cssClassAction)
            {
            }

            public Dl(string cssClass) : base("Dl", cssClass)
            {
            }
        }

        public record Dt : Styled
        {
            public Dt() : base("dt")
            {
            }

            public Dt(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Dt", cssClassAction)
            {
            }

            public Dt(string cssClass) : base("Dt", cssClass)
            {
            }
        }

        public record Em : Styled
        {
            public Em() : base("em")
            {
            }

            public Em(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Em", cssClassAction)
            {
            }

            public Em(string cssClass) : base("Em", cssClass)
            {
            }
        }

        public record Embed : Styled
        {
            public Embed() : base("embed")
            {
            }

            public Embed(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Embed", cssClassAction)
            {
            }

            public Embed(string cssClass) : base("Embed", cssClass)
            {
            }
        }

        public record Fieldset : Styled
        {
            public Fieldset() : base("fieldset")
            {
            }

            public Fieldset(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Fieldset", cssClassAction)
            {
            }

            public Fieldset(string cssClass) : base("Fieldset", cssClass)
            {
            }
        }

        public record Figcaption : Styled
        {
            public Figcaption() : base("figcaption")
            {
            }

            public Figcaption(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Figcaption", cssClassAction)
            {
            }

            public Figcaption(string cssClass) : base("Figcaption", cssClass)
            {
            }
        }

        public record Figure : Styled
        {
            public Figure() : base("figure")
            {
            }

            public Figure(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Figure", cssClassAction)
            {
            }

            public Figure(string cssClass) : base("Figure", cssClass)
            {
            }
        }

        public record Footer : Styled
        {
            public Footer() : base("footer")
            {
            }

            public Footer(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Footer", cssClassAction)
            {
            }

            public Footer(string cssClass) : base("Footer", cssClass)
            {
            }
        }

        public record Form : Styled
        {
            public Form() : base("form")
            {
            }

            public Form(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Form", cssClassAction)
            {
            }

            public Form(string cssClass) : base("Form", cssClass)
            {
            }
        }

        public record H1 : Styled
        {
            public H1() : base("h1")
            {
            }

            public H1(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H1", cssClassAction)
            {
            }

            public H1(string cssClass) : base("H1", cssClass)
            {
            }
        }

        public record H2 : Styled
        {
            public H2() : base("h2")
            {
            }

            public H2(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H2", cssClassAction)
            {
            }

            public H2(string cssClass) : base("H2", cssClass)
            {
            }
        }

        public record H3 : Styled
        {
            public H3() : base("h3")
            {
            }

            public H3(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H3", cssClassAction)
            {
            }

            public H3(string cssClass) : base("H3", cssClass)
            {
            }
        }

        public record H4 : Styled
        {
            public H4() : base("h4")
            {
            }

            public H4(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H4", cssClassAction)
            {
            }

            public H4(string cssClass) : base("H4", cssClass)
            {
            }
        }

        public record H5 : Styled
        {
            public H5() : base("h5")
            {
            }

            public H5(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H5", cssClassAction)
            {
            }

            public H5(string cssClass) : base("H5", cssClass)
            {
            }
        }

        public record H6 : Styled
        {
            public H6() : base("h6")
            {
            }

            public H6(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("H6", cssClassAction)
            {
            }

            public H6(string cssClass) : base("H6", cssClass)
            {
            }
        }

        public record Head : Styled
        {
            public Head() : base("head")
            {
            }

            public Head(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Head", cssClassAction)
            {
            }

            public Head(string cssClass) : base("Head", cssClass)
            {
            }
        }

        public record Header : Styled
        {
            public Header() : base("header")
            {
            }

            public Header(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Header", cssClassAction)
            {
            }

            public Header(string cssClass) : base("Header", cssClass)
            {
            }
        }

        public record Hgroup : Styled
        {
            public Hgroup() : base("hgroup")
            {
            }

            public Hgroup(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Hgroup", cssClassAction)
            {
            }

            public Hgroup(string cssClass) : base("Hgroup", cssClass)
            {
            }
        }

        public record Hr : Styled
        {
            public Hr() : base("hr")
            {
            }

            public Hr(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Hr", cssClassAction)
            {
            }

            public Hr(string cssClass) : base("Hr", cssClass)
            {
            }
        }

        public record Html : Styled
        {
            public Html() : base("html")
            {
            }

            public Html(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Html", cssClassAction)
            {
            }

            public Html(string cssClass) : base("Html", cssClass)
            {
            }
        }

        public record I : Styled
        {
            public I() : base("i")
            {
            }

            public I(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("I", cssClassAction)
            {
            }

            public I(string cssClass) : base("I", cssClass)
            {
            }
        }

        public record Iframe : Styled
        {
            public Iframe() : base("iframe")
            {
            }

            public Iframe(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Iframe", cssClassAction)
            {
            }

            public Iframe(string cssClass) : base("Iframe", cssClass)
            {
            }
        }

        public record Img : Styled
        {
            public Img() : base("img")
            {
            }

            public Img(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Img", cssClassAction)
            {
            }

            public Img(string cssClass) : base("Img", cssClass)
            {
            }
        }

        public record Input : Styled
        {
            public Input() : base("input")
            {
            }

            public Input(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Input", cssClassAction)
            {
            }

            public Input(string cssClass) : base("Input", cssClass)
            {
            }
        }

        public record Ins : Styled
        {
            public Ins() : base("ins")
            {
            }

            public Ins(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Ins", cssClassAction)
            {
            }

            public Ins(string cssClass) : base("Ins", cssClass)
            {
            }
        }

        public record Kbd : Styled
        {
            public Kbd() : base("kbd")
            {
            }

            public Kbd(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Kbd", cssClassAction)
            {
            }

            public Kbd(string cssClass) : base("Kbd", cssClass)
            {
            }
        }

        public record Keygen : Styled
        {
            public Keygen() : base("keygen")
            {
            }

            public Keygen(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Keygen", cssClassAction)
            {
            }

            public Keygen(string cssClass) : base("Keygen", cssClass)
            {
            }
        }

        public record Label : Styled
        {
            public Label() : base("label")
            {
            }

            public Label(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Label", cssClassAction)
            {
            }

            public Label(string cssClass) : base("Label", cssClass)
            {
            }
        }

        public record Legend : Styled
        {
            public Legend() : base("legend")
            {
            }

            public Legend(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Legend", cssClassAction)
            {
            }

            public Legend(string cssClass) : base("Legend", cssClass)
            {
            }
        }

        public record Li : Styled
        {
            public Li() : base("li")
            {
            }

            public Li(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Li", cssClassAction)
            {
            }

            public Li(string cssClass) : base("Li", cssClass)
            {
            }
        }

        public record Link : Styled
        {
            public Link() : base("link")
            {
            }

            public Link(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Link", cssClassAction)
            {
            }

            public Link(string cssClass) : base("Link", cssClass)
            {
            }
        }

        public record Main : Styled
        {
            public Main() : base("main")
            {
            }

            public Main(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Main", cssClassAction)
            {
            }

            public Main(string cssClass) : base("Main", cssClass)
            {
            }
        }

        public record Map : Styled
        {
            public Map() : base("map")
            {
            }

            public Map(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Map", cssClassAction)
            {
            }

            public Map(string cssClass) : base("Map", cssClass)
            {
            }
        }

        public record Mark : Styled
        {
            public Mark() : base("mark")
            {
            }

            public Mark(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Mark", cssClassAction)
            {
            }

            public Mark(string cssClass) : base("Mark", cssClass)
            {
            }
        }

        public record Marquee : Styled
        {
            public Marquee() : base("marquee")
            {
            }

            public Marquee(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Marquee", cssClassAction)
            {
            }

            public Marquee(string cssClass) : base("Marquee", cssClass)
            {
            }
        }

        public record Menu : Styled
        {
            public Menu() : base("menu")
            {
            }

            public Menu(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Menu", cssClassAction)
            {
            }

            public Menu(string cssClass) : base("Menu", cssClass)
            {
            }
        }

        public record Menuitem : Styled
        {
            public Menuitem() : base("menuitem")
            {
            }

            public Menuitem(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Menuitem", cssClassAction)
            {
            }

            public Menuitem(string cssClass) : base("Menuitem", cssClass)
            {
            }
        }

        public record Meta : Styled
        {
            public Meta() : base("meta")
            {
            }

            public Meta(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Meta", cssClassAction)
            {
            }

            public Meta(string cssClass) : base("Meta", cssClass)
            {
            }
        }

        public record Meter : Styled
        {
            public Meter() : base("meter")
            {
            }

            public Meter(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Meter", cssClassAction)
            {
            }

            public Meter(string cssClass) : base("Meter", cssClass)
            {
            }
        }

        public record Nav : Styled
        {
            public Nav() : base("nav")
            {
            }

            public Nav(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Nav", cssClassAction)
            {
            }

            public Nav(string cssClass) : base("Nav", cssClass)
            {
            }
        }

        public record Noscript : Styled
        {
            public Noscript() : base("noscript")
            {
            }

            public Noscript(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Noscript", cssClassAction)
            {
            }

            public Noscript(string cssClass) : base("Noscript", cssClass)
            {
            }
        }

        public record Object : Styled
        {
            public Object() : base("object")
            {
            }

            public Object(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Object", cssClassAction)
            {
            }

            public Object(string cssClass) : base("Object", cssClass)
            {
            }
        }

        public record Ol : Styled
        {
            public Ol() : base("ol")
            {
            }

            public Ol(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Ol", cssClassAction)
            {
            }

            public Ol(string cssClass) : base("Ol", cssClass)
            {
            }
        }

        public record Optgroup : Styled
        {
            public Optgroup() : base("optgroup")
            {
            }

            public Optgroup(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Optgroup", cssClassAction)
            {
            }

            public Optgroup(string cssClass) : base("Optgroup", cssClass)
            {
            }
        }

        public record Option : Styled
        {
            public Option() : base("option")
            {
            }

            public Option(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Option", cssClassAction)
            {
            }

            public Option(string cssClass) : base("Option", cssClass)
            {
            }
        }

        public record Output : Styled
        {
            public Output() : base("output")
            {
            }

            public Output(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Output", cssClassAction)
            {
            }

            public Output(string cssClass) : base("Output", cssClass)
            {
            }
        }

        public record P : Styled
        {
            public P() : base("p")
            {
            }

            public P(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("P", cssClassAction)
            {
            }

            public P(string cssClass) : base("P", cssClass)
            {
            }
        }

        public record Param : Styled
        {
            public Param() : base("param")
            {
            }

            public Param(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Param", cssClassAction)
            {
            }

            public Param(string cssClass) : base("Param", cssClass)
            {
            }
        }

        public record Picture : Styled
        {
            public Picture() : base("picture")
            {
            }

            public Picture(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Picture", cssClassAction)
            {
            }

            public Picture(string cssClass) : base("Picture", cssClass)
            {
            }
        }

        public record Pre : Styled
        {
            public Pre() : base("pre")
            {
            }

            public Pre(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Pre", cssClassAction)
            {
            }

            public Pre(string cssClass) : base("Pre", cssClass)
            {
            }
        }

        public record Progress : Styled
        {
            public Progress() : base("progress")
            {
            }

            public Progress(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Progress", cssClassAction)
            {
            }

            public Progress(string cssClass) : base("Progress", cssClass)
            {
            }
        }

        public record Q : Styled
        {
            public Q() : base("q")
            {
            }

            public Q(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Q", cssClassAction)
            {
            }

            public Q(string cssClass) : base("Q", cssClass)
            {
            }
        }

        public record Rp : Styled
        {
            public Rp() : base("rp")
            {
            }

            public Rp(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Rp", cssClassAction)
            {
            }

            public Rp(string cssClass) : base("Rp", cssClass)
            {
            }
        }

        public record Rt : Styled
        {
            public Rt() : base("rt")
            {
            }

            public Rt(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Rt", cssClassAction)
            {
            }

            public Rt(string cssClass) : base("Rt", cssClass)
            {
            }
        }

        public record Ruby : Styled
        {
            public Ruby() : base("ruby")
            {
            }

            public Ruby(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Ruby", cssClassAction)
            {
            }

            public Ruby(string cssClass) : base("Ruby", cssClass)
            {
            }
        }

        public record S : Styled
        {
            public S() : base("s")
            {
            }

            public S(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("S", cssClassAction)
            {
            }

            public S(string cssClass) : base("S", cssClass)
            {
            }
        }

        public record Samp : Styled
        {
            public Samp() : base("samp")
            {
            }

            public Samp(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Samp", cssClassAction)
            {
            }

            public Samp(string cssClass) : base("Samp", cssClass)
            {
            }
        }

        public record Script : Styled
        {
            public Script() : base("script")
            {
            }

            public Script(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Script", cssClassAction)
            {
            }

            public Script(string cssClass) : base("Script", cssClass)
            {
            }
        }

        public record Section : Styled
        {
            public Section() : base("section")
            {
            }

            public Section(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Section", cssClassAction)
            {
            }

            public Section(string cssClass) : base("Section", cssClass)
            {
            }
        }

        public record Select : Styled
        {
            public Select() : base("select")
            {
            }

            public Select(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Select", cssClassAction)
            {
            }

            public Select(string cssClass) : base("Select", cssClass)
            {
            }
        }

        public record Small : Styled
        {
            public Small() : base("small")
            {
            }

            public Small(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Small", cssClassAction)
            {
            }

            public Small(string cssClass) : base("Small", cssClass)
            {
            }
        }

        public record Source : Styled
        {
            public Source() : base("source")
            {
            }

            public Source(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Source", cssClassAction)
            {
            }

            public Source(string cssClass) : base("Source", cssClass)
            {
            }
        }

        public record Span : Styled
        {
            public Span() : base("span")
            {
            }

            public Span(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Span", cssClassAction)
            {
            }

            public Span(string cssClass) : base("Span", cssClass)
            {
            }
        }

        public record Strong : Styled
        {
            public Strong() : base("strong")
            {
            }

            public Strong(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Strong", cssClassAction)
            {
            }

            public Strong(string cssClass) : base("Strong", cssClass)
            {
            }
        }

        public record Style : Styled
        {
            public Style() : base("style")
            {
            }

            public Style(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Style", cssClassAction)
            {
            }

            public Style(string cssClass) : base("Style", cssClass)
            {
            }
        }

        public record Sub : Styled
        {
            public Sub() : base("sub")
            {
            }

            public Sub(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Sub", cssClassAction)
            {
            }

            public Sub(string cssClass) : base("Sub", cssClass)
            {
            }
        }

        public record Summary : Styled
        {
            public Summary() : base("summary")
            {
            }

            public Summary(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Summary", cssClassAction)
            {
            }

            public Summary(string cssClass) : base("Summary", cssClass)
            {
            }
        }

        public record Sup : Styled
        {
            public Sup() : base("sup")
            {
            }

            public Sup(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Sup", cssClassAction)
            {
            }

            public Sup(string cssClass) : base("Sup", cssClass)
            {
            }
        }

        public record Table : Styled
        {
            public Table() : base("table")
            {
            }

            public Table(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Table", cssClassAction)
            {
            }

            public Table(string cssClass) : base("Table", cssClass)
            {
            }
        }

        public record Tbody : Styled
        {
            public Tbody() : base("tbody")
            {
            }

            public Tbody(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Tbody", cssClassAction)
            {
            }

            public Tbody(string cssClass) : base("Tbody", cssClass)
            {
            }
        }

        public record Td : Styled
        {
            public Td() : base("td")
            {
            }

            public Td(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Td", cssClassAction)
            {
            }

            public Td(string cssClass) : base("Td", cssClass)
            {
            }
        }

        public record Textarea : Styled
        {
            public Textarea() : base("textarea")
            {
            }

            public Textarea(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Textarea", cssClassAction)
            {
            }

            public Textarea(string cssClass) : base("Textarea", cssClass)
            {
            }
        }

        public record Tfoot : Styled
        {
            public Tfoot() : base("tfoot")
            {
            }

            public Tfoot(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Tfoot", cssClassAction)
            {
            }

            public Tfoot(string cssClass) : base("Tfoot", cssClass)
            {
            }
        }

        public record Th : Styled
        {
            public Th() : base("th")
            {
            }

            public Th(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Th", cssClassAction)
            {
            }

            public Th(string cssClass) : base("Th", cssClass)
            {
            }
        }

        public record Thead : Styled
        {
            public Thead() : base("thead")
            {
            }

            public Thead(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Thead", cssClassAction)
            {
            }

            public Thead(string cssClass) : base("Thead", cssClass)
            {
            }
        }

        public record Time : Styled
        {
            public Time() : base("time")
            {
            }

            public Time(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Time", cssClassAction)
            {
            }

            public Time(string cssClass) : base("Time", cssClass)
            {
            }
        }

        public record Title : Styled
        {
            public Title() : base("title")
            {
            }

            public Title(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Title", cssClassAction)
            {
            }

            public Title(string cssClass) : base("Title", cssClass)
            {
            }
        }

        public record Tr : Styled
        {
            public Tr() : base("tr")
            {
            }

            public Tr(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Tr", cssClassAction)
            {
            }

            public Tr(string cssClass) : base("Tr", cssClass)
            {
            }
        }

        public record Track : Styled
        {
            public Track() : base("track")
            {
            }

            public Track(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Track", cssClassAction)
            {
            }

            public Track(string cssClass) : base("Track", cssClass)
            {
            }
        }

        public record U : Styled
        {
            public U() : base("u")
            {
            }

            public U(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("U", cssClassAction)
            {
            }

            public U(string cssClass) : base("U", cssClass)
            {
            }
        }

        public record Ul : Styled
        {
            public Ul() : base("ul")
            {
            }

            public Ul(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Ul", cssClassAction)
            {
            }

            public Ul(string cssClass) : base("Ul", cssClass)
            {
            }
        }

        public record Var : Styled
        {
            public Var() : base("var")
            {
            }

            public Var(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Var", cssClassAction)
            {
            }

            public Var(string cssClass) : base("Var", cssClass)
            {
            }
        }

        public record Video : Styled
        {
            public Video() : base("video")
            {
            }

            public Video(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Video", cssClassAction)
            {
            }

            public Video(string cssClass) : base("Video", cssClass)
            {
            }
        }

        public record Wbr : Styled
        {
            public Wbr() : base("wbr")
            {
            }

            public Wbr(Func<Dictionary<string, string>, IEnumerable<string>> cssClassAction) : base("Wbr", cssClassAction)
            {
            }

            public Wbr(string cssClass) : base("Wbr", cssClass)
            {
            }
        }
    }
}
